import { Inter } from 'next/font/google'
import './globals.css'
import HeaderComponent from "@/app/components/HeaderComponent/HeaderComponent";
import FooterComponent from "@/app/components/FooterComponent/FooterComponent";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderComponent/>
      <div className={"flex justify-center"}>
          {children}
      </div>
      <FooterComponent/>
      </body>
    </html>
  )
}
